apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-test-deployment
spec:
  selector:
    matchLabels:
      app: websocket-test
  replicas: 12
  template:
    metadata:
      labels:
        app: websocket-test
    spec:
      containers:
        - name: websocket-test
          image: kuthia/websocket-test
          ports:
          - containerPort: 8010
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
      restartPolicy: "Always"
---
apiVersion: v1
kind: Service
metadata:
  name: test-websocket-nginx
spec:
  type: LoadBalancer
  ports:
    - name: "http-websocket-test"
      port: 8010
      targetPort: 8010
  selector:
    app: websocket-test
status:
  loadBalancer: {}

